version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links: 
      - database
    ports: 
      - 8080:8080
      - 1236:1236
      - 26162:26162
    volumes:
      - ./src:/opt/app

  database:
    image: postgres:11.3
    ports:
      - 5432:5432
