version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links: 
      - database
    ports: 
      - 8080:8080
      - 1236:1236
    volumes:
      - ./src:/opt/app
    environment:
      IDE_PROCESS_DISPATCHER : docker.for.mac.localhost:26162

  database:
    image: postgres:11.3
    ports:
      - 5432:5432
